spring:
  profiles:
    active: dev  # 默认在本地跑，激活 dev 环境
  application:
    name: croprogram-backend # 你的应用名
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true